version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    reviewers:
      - "dewetblomerus"
