title: De Wet Blomerus
email: dewetblomerus@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dewetblomerus.com" # the base hostname & protocol for your site
github_username: dewetblomerus
linkedin_username: dewetblomerus

# Build settings
theme: minima
port: 3000
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Disqus comments
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: true
